# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/pathanasiadis/cmake-4.2.1-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/pathanasiadis/cmake-4.2.1-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pathanasiadis/performance

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pathanasiadis/performance

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/pathanasiadis/cmake-4.2.1-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/pathanasiadis/cmake-4.2.1-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pathanasiadis/performance/CMakeFiles /home/pathanasiadis/performance//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pathanasiadis/performance/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named navier_stokes_gpu

# Build rule for target.
navier_stokes_gpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 navier_stokes_gpu
.PHONY : navier_stokes_gpu

# fast build rule for target.
navier_stokes_gpu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/build
.PHONY : navier_stokes_gpu/fast

src/coordinates.o: src/coordinates.cu.o
.PHONY : src/coordinates.o

# target to build an object file
src/coordinates.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/coordinates.cu.o
.PHONY : src/coordinates.cu.o

src/coordinates.i: src/coordinates.cu.i
.PHONY : src/coordinates.i

# target to preprocess a source file
src/coordinates.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/coordinates.cu.i
.PHONY : src/coordinates.cu.i

src/coordinates.s: src/coordinates.cu.s
.PHONY : src/coordinates.s

# target to generate assembly for a file
src/coordinates.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/coordinates.cu.s
.PHONY : src/coordinates.cu.s

src/kernels.o: src/kernels.cu.o
.PHONY : src/kernels.o

# target to build an object file
src/kernels.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/kernels.cu.o
.PHONY : src/kernels.cu.o

src/kernels.i: src/kernels.cu.i
.PHONY : src/kernels.i

# target to preprocess a source file
src/kernels.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/kernels.cu.i
.PHONY : src/kernels.cu.i

src/kernels.s: src/kernels.cu.s
.PHONY : src/kernels.s

# target to generate assembly for a file
src/kernels.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/kernels.cu.s
.PHONY : src/kernels.cu.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/navier_stokes.o: src/navier_stokes.cu.o
.PHONY : src/navier_stokes.o

# target to build an object file
src/navier_stokes.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/navier_stokes.cu.o
.PHONY : src/navier_stokes.cu.o

src/navier_stokes.i: src/navier_stokes.cu.i
.PHONY : src/navier_stokes.i

# target to preprocess a source file
src/navier_stokes.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/navier_stokes.cu.i
.PHONY : src/navier_stokes.cu.i

src/navier_stokes.s: src/navier_stokes.cu.s
.PHONY : src/navier_stokes.s

# target to generate assembly for a file
src/navier_stokes.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/navier_stokes.cu.s
.PHONY : src/navier_stokes.cu.s

src/solver.o: src/solver.cu.o
.PHONY : src/solver.o

# target to build an object file
src/solver.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/solver.cu.o
.PHONY : src/solver.cu.o

src/solver.i: src/solver.cu.i
.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/solver.cu.i
.PHONY : src/solver.cu.i

src/solver.s: src/solver.cu.s
.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/navier_stokes_gpu.dir/build.make CMakeFiles/navier_stokes_gpu.dir/src/solver.cu.s
.PHONY : src/solver.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... navier_stokes_gpu"
	@echo "... src/coordinates.o"
	@echo "... src/coordinates.i"
	@echo "... src/coordinates.s"
	@echo "... src/kernels.o"
	@echo "... src/kernels.i"
	@echo "... src/kernels.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/navier_stokes.o"
	@echo "... src/navier_stokes.i"
	@echo "... src/navier_stokes.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

